/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f9f9f8',
        'surface-dim': '#dadad9',
        'surface-bright': '#f9f9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f3',
        'surface-container': '#eeeeed',
        'surface-container-high': '#e8e8e7',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#45464d',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f1f0',
        'outline': '#76777d',
        'outline-variant': '#c6c6cd',
        'surface-tint': '#565e74',
        'primary': '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'inverse-primary': '#bec6e0',
        'secondary': '#775a19',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed488',
        'on-secondary-container': '#785a1a',
        'tertiary': '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#0d1c2e',
        'on-tertiary-container': '#77859a',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary-fixed': '#d5e3fc',
        'tertiary-fixed-dim': '#b9c7df',
        'on-tertiary-fixed': '#0d1c2e',
        'on-tertiary-fixed-variant': '#3a485b',
        'background': '#f9f9f8',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'unit': '4px',
        'container-max': '1440px',
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '24px',
        'hairline': '1px',
      },
      fontFamily: {
        'headline-lg-mobile': ['EB Garamond', 'serif'],
        'display-lg':         ['EB Garamond', 'serif'],
        'display-md':         ['EB Garamond', 'serif'],
        'headline-lg':        ['EB Garamond', 'serif'],
        'headline-md':        ['EB Garamond', 'serif'],
        'body-lg':            ['Geist', 'sans-serif'],
        'body-md':            ['Geist', 'sans-serif'],
        'label-md':           ['Geist', 'sans-serif'],
        'label-sm':           ['Geist', 'sans-serif'],
        'garamond':           ['EB Garamond', 'serif'],
        'grotesk':            ['Geist', 'sans-serif'],
        'inter':              ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg':         ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-md':         ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg':        ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-md':        ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg':            ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md':           ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm':           ['12px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-md-mobile': ['30px', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-xs': ['22px', { lineHeight: '1.3', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
